package my:test;

interface i {
  pending-import: async func(x: future);
  backpressure-set: func(x: bool);
}

world test {
  include wasi:cli/imports@0.2.6;
  export i;
}

world runner {
  import i;
}
