name: CI

on:
  pull_request:
  merge_group:

defaults:
  run:
    shell: bash

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  async:
    name: Test Async (allowed to fail)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Rust
      run: rustup update stable --no-self-update && rustup default stable
    - run: rustup target add wasm32-wasip1
    - uses: ./.github/actions/install-wasi-sdk
    - run: |
        curl -L https://github.com/bytecodealliance/wasip3-prototyping/releases/download/dev/wasmtime-dev-x86_64-linux.tar.xz | tar xJvf -
        echo "WASMTIME=`pwd`/wasmtime-dev-x86_64-linux/wasmtime" >> $GITHUB_ENV
    - run: |
        cargo run test --languages rust,c tests/runtime-async/async/cancel-import \
          --artifacts target/artifacts \
          --rust-wit-bindgen-path ./crates/guest-rust \
          --rust-target wasm32-wasip1 \
          --c-target wasm32-wasip1 \
          --runner "$WASMTIME -W component-model-async"
